### ISSUE TITLE
Some puzzle about Table 1 and Supplementary Information

### ISSUE THREAD

**Issue by robNavLoc** [darioizzo/geodesyNets#114]
Hello, Dario and Pablo:
    I have carefully read your work (including the paper, supplementary information, and code), and I believe that your work is very useful and innovative in the forward and backward modeling of gravitational fields in small bodies.
    But I have a small question. **I cannot find the results in Table 1 (which may include Table 3) from the 'Supplementary Information' (geodesyAnn_data/results/Without Body Shape/Homogeneous/.../.../validation_results.csv). The values of altitudes and errors do not correspond to each other.** _Is this phenomenon caused by non-dimensional (Table S3)? If YES, Is there any function in the code that converts non-dimensional results into normal results?_
Hope to receive your reply and answer, Thanks very much!
Duan Yabo

**Comment by gomezzz** [comment]
Hi @robNavLoc ,
thank you for your interest and kind words. Yes, for the paper we converted from non-dimensional (as in the code) to SI units (in the table). You can find the conversion factors in the notebooks in some of the last cells
https://github.com/darioizzo/geodesyNets/blob/master/1%20-%20Direct%20training.ipynb

In particular
```
factor_planetesimal = 9.982e12 * 6.67430e-11 / 3126.6064453124995**2
factor_itokawa = 3.51e10 * 6.67430e-11 / 350.438691675663**2
factor_eros = 6.687e15 * 6.67430e-11 / 20413.864850997925**2
factor_bennu = (7.329e10   * 6.67430e-11  / 352.1486930549145**2)
factor_67p = 9.982e12 * 6.67430e-11 / 3126.6064453124995**2
```

Does this answer your question? :)

**Comment by robNavLoc** [comment]
> Hi @robNavLoc , thank you for your interest and kind words. Yes, for the paper we converted from non-dimensional (as in the code) to SI units (in the table). You can find the conversion factors in the notebooks in some of the last cells https://github.com/darioizzo/geodesyNets/blob/master/1%20-%20Direct%20training.ipynb
> 
> In particular
> 
> ```
> factor_planetesimal = 9.982e12 * 6.67430e-11 / 3126.6064453124995**2
> factor_itokawa = 3.51e10 * 6.67430e-11 / 350.438691675663**2
> factor_eros = 6.687e15 * 6.67430e-11 / 20413.864850997925**2
> factor_bennu = (7.329e10   * 6.67430e-11  / 352.1486930549145**2)
> factor_67p = 9.982e12 * 6.67430e-11 / 3126.6064453124995**2
> ```
> 
> Does this answer your question? :)

Hello Pablo, thanks very much for your reply. I have noticed this part of the code, but there is still a small puzzle.

Isn't the result presented here(**geodesyAnn_data/results/Without Body Shape/ and ./Differential Training**) the final version of the paper? I see that the results here are different from those in **Table 1 and Table 3** of the paper (Even after unifying the unit).

I'm very sorry to bother you again, but I still hope to receive your answer！
Duan Yabo

**Comment by gomezzz** [comment]
Hi @robNavLoc ,

ah sorry I misunderstood the question. 
Are you maybe looking at the arxiv version? Some improvements were made later, see the table here https://www.nature.com/articles/s44172-022-00050-3/tables/1 in the final published version. Those numbers should match, I think?

**Comment by gomezzz** [comment]
( iirc the change was due the choice of the grid for the numerical integration, which had used different points in the validation than in training in the original version. That led to higher errors since we were basically evaluating on different points than in training and was remedied during the revision process)

**Comment by robNavLoc** [comment]
Thanks very much~ All puzzles have been answered, and I closed this comment. Thanks again.
